// Aplication Actions
// export const CHANGE_MSG = "CHANGE_MSG";

// Usuario Actions
export const CHANGE_NOME_USUARIO = "CHANGE_NOME_USUARIO";
export const CHANGE_EMAIL_USUARIO = "CHANGE_EMAIL_USUARIO";
export const CHANGE_SENHA_USUARIO = "CHANGE_SENHA_USUARIO";
export const CHANGE_CONFIRMAR_SENHA_USUARIO = "CHANGE_CONFIRMAR_SENHA_USUARIO";
export const CHANGE_TELEFONE_USUARIO = "CHANGE_TELEFONE_USUARIO";

export const CHANGE_MSG_NOME_INVALID_USUARIO = "CHANGE_MSG_NOME_INVALID_USUARIO";
export const CHANGE_MSG_EMAIL_INVALID_USUARIO = "CHANGE_MSG_EMAIL_INVALID_USUARIO";
export const CHANGE_MSG_SENHA_INVALID_USUARIO = "CHANGE_MSG_SENHA_INVALID_USUARIO";
export const CHANGE_MSG_CONFIRMAR_SENHA_INVALID_USUARIO = "CHANGE_MSG_CONFIRMAR_SENHA_INVALID_USUARIO";
export const CHANGE_MSG_TELEFONE_INVALID_USUARIO = "CHANGE_MSG_TELEFONE_INVALID_USUARIO";

export const RESET_CAMPOS_USUARIO = "RESET_CAMPOS_USUARIO";
// export const CHANGE_PERFIL_USUARIO = "CHANGE_PERFIL_USUARIO";
// export const CHANGE_AUTH_USUARIO = "CHANGE_AUTH_USUARIO";

// Servicos Actions
// export const GET_SERVICOS = "GET_SERVICOS";
// export const CHANGE_NOME_SERVICO = "CHANGE_NOME_SERVICO";
// export const CHANGE_INSTRUTOR_SERVICO = "CHANGE_INSTRUTOR_SERVICO";
// export const CHANGE_PRECO_SERVICO = "CHANGE_PRECO_SERVICO";
// export const CHANGE_IMAGEM_NOME_SERVICO = "CHANGE_IMAGEM_NOME_SERVICO";